### ISSUE TITLE
FFMPEG build failed: duplicate symbol between ffmpeg and libbluray

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#633]
The problem is introduced by https://github.com/FFmpeg/FFmpeg/commit/c4de5778bceab3c15f1239f1f16816749a7fd3b6 
build log:
```
ld.lld: error: duplicate symbol: dec_init
>>> defined at src/fftools/ffmpeg_dec.c
>>>            fftools/ffmpeg_dec.o
>>> defined at src/libbluray/disc/dec.c
>>>            libbluray.a(libbluray_la-dec.o)
```

**Comment by zhongfly** [comment]
> `-Wl,--allow-multiple-definition`

These options allow multiple definitions and the **first definition will be used**.

In ffmpeg and libbluary, the definition of `dec_init` is completely different, they just have the same name
